export type TabType = "news" | "cartoon" | "games";

export const content: Record<TabType, string[]> = {
  news: [
    "Breaking: React 19 Released!",
    "Vite 5.0 now supports faster HMR",
    "Tailwind CSS introduces new animations",
  ],
  cartoon: [
    "Mickey Mouse Adventures",
    "Tom & Jerry Classics",
    "SpongeBob SquarePants",
  ],
  games: ["Chess", "Ludo", "Tic-Tac-Toe"],
};
export const Contributor = [
  {
    id: 6,
    name: "Geet Srivastava",
    avatar:
      "https://res.cloudinary.com/doytvgisa/image/upload/v1758643144/Geet_y3etiz.jpg",
    contributions: 10,
    role: "Figma Expert",
    joinDate: "Sep 2025",
    specialties: ["Figma", "Java", "Backend"],
    isTopContributor: false,
    from: 'BBD University'
  },
  {
    id: 7,
    name: "Pranjal Gupta",
    avatar:
      "https://res.cloudinary.com/doytvgisa/image/upload/v1758643144/Geet_y3etiz.jpg",
    contributions: 10,
    role: "AI & ML",
    joinDate: "Oct 2025",
    specialties: ["C", "Python", "Tkinter"],
    isTopContributor: false,
    from: 'BBD University'
  },
  {
    id: 8,
    name: "Akshara Dixit",
    avatar:
      "https://res.cloudinary.com/doytvgisa/image/upload/v1758643144/Geet_y3etiz.jpg",
    contributions: 10,
    role: "Web Development",
    joinDate: "Oct 2025",
    specialties: ["C", "Problem Solving"],
    isTopContributor: false,
    from: 'BBD University'
  },

]

export const companies = [
  {
    "id": 1,
    "company_name": "Google",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Python", "System Design", "Data Structures"],
    "experience_required": "0-2 years",
    "package_lpa": 18.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 2,
    "company_name": "Microsoft",
    "industry": "Technology",
    "location": "Hyderabad, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["C++", "Azure", "Cloud Computing", "Algorithms"],
    "experience_required": "0-2 years",
    "package_lpa": 19.2,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 3,
    "company_name": "Amazon",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer I",
    "required_skills": ["Java", "AWS", "Distributed Systems", "OOP"],
    "experience_required": "0-1 years",
    "package_lpa": 17.8,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2024-2025 Batch"
  },
  {
    "id": 4,
    "company_name": "OpenAI",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "AI Research Engineer",
    "required_skills": ["Python", "Machine Learning", "Deep Learning", "PyTorch"],
    "experience_required": "0-2 years",
    "package_lpa": 25.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/AI/ML",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 5,
    "company_name": "Adobe",
    "industry": "Technology",
    "location": "Noida, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["C++", "Algorithms", "Graphics", "Design Patterns"],
    "experience_required": "0-1 years",
    "package_lpa": 20.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 6,
    "company_name": "Nvidia",
    "industry": "Technology",
    "location": "Pune, India",
    "job_role": "AI Software Engineer",
    "required_skills": ["C++", "CUDA", "Deep Learning", "Computer Vision"],
    "experience_required": "0-1 years",
    "package_lpa": 21.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 7,
    "company_name": "Meta",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Python", "React", "Backend Development", "System Design"],
    "experience_required": "0-2 years",
    "package_lpa": 22.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 8,
    "company_name": "Apple",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Swift", "Objective-C", "iOS Development", "Algorithms"],
    "experience_required": "0-2 years",
    "package_lpa": 23.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 9,
    "company_name": "Salesforce",
    "industry": "Technology",
    "location": "Hyderabad, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Cloud Computing", "Apex", "Lightning"],
    "experience_required": "0-1 years",
    "package_lpa": 16.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 10,
    "company_name": "Intuit",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer 1",
    "required_skills": ["Java", "Spring Boot", "React", "Microservices"],
    "experience_required": "0-1 years",
    "package_lpa": 18.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 11,
    "company_name": "IBM",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "AI Developer",
    "required_skills": ["Python", "Watson AI", "Machine Learning", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 14.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/AI",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 12,
    "company_name": "Oracle",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Developer",
    "required_skills": ["Java", "SQL", "PL/SQL", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 12.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 13,
    "company_name": "SAP Labs",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Developer Associate",
    "required_skills": ["Java", "SAP HANA", "Cloud", "Database"],
    "experience_required": "0-1 years",
    "package_lpa": 13.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 14,
    "company_name": "VMware",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["C++", "Java", "Virtualization", "Cloud"],
    "experience_required": "0-1 years",
    "package_lpa": 17.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 15,
    "company_name": "Atlassian",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "React", "Spring Boot", "Microservices"],
    "experience_required": "0-2 years",
    "package_lpa": 19.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 16,
    "company_name": "Flipkart",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Spring Boot", "Microservices", "SQL"],
    "experience_required": "0-2 years",
    "package_lpa": 15.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batchz"
  },
  {
    "id": 17,
    "company_name": "Walmart Labs",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer II",
    "required_skills": ["Java", "React", "Microservices", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 16.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 18,
    "company_name": "Uber",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer I",
    "required_skills": ["Go", "Java", "Distributed Systems", "Kafka"],
    "experience_required": "0-2 years",
    "package_lpa": 19.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 19,
    "company_name": "Razorpay",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Python", "Go", "Payment Systems", "APIs"],
    "experience_required": "0-2 years",
    "package_lpa": 14.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 20,
    "company_name": "PhonePe",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Kotlin", "Microservices", "Distributed Systems"],
    "experience_required": "0-2 years",
    "package_lpa": 15.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 21,
    "company_name": "Swiggy",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Spring Boot", "Kafka", "Redis"],
    "experience_required": "0-2 years",
    "package_lpa": 13.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 22,
    "company_name": "Zomato",
    "industry": "Technology",
    "location": "Gurgaon, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Python", "Django", "Microservices", "SQL"],
    "experience_required": "0-2 years",
    "package_lpa": 12.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 23,
    "company_name": "Meesho",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Spring Boot", "Kafka", "Redis"],
    "experience_required": "0-2 years",
    "package_lpa": 14.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 24,
    "company_name": "Myntra",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "React", "Microservices", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 13.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 25,
    "company_name": "Thoughtworks",
    "industry": "Technology",
    "location": "Multiple Locations",
    "job_role": "Software Developer",
    "required_skills": ["Java", "Python", "Agile", "TDD"],
    "experience_required": "0-2 years",
    "package_lpa": 12.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 26,
    "company_name": "Paytm",
    "industry": "Technology",
    "location": "Noida, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Android", "Backend", "APIs"],
    "experience_required": "0-2 years",
    "package_lpa": 10.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 27,
    "company_name": "Anthropic",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "AI Safety Engineer",
    "required_skills": ["Python", "Machine Learning", "NLP", "Reinforcement Learning"],
    "experience_required": "0-2 years",
    "package_lpa": 26.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/AI",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 28,
    "company_name": "DeepMind",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Research Engineer - AI",
    "required_skills": ["Python", "TensorFlow", "Deep Learning", "Research"],
    "experience_required": "0-2 years",
    "package_lpa": 28.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/AI/ML",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 29,
    "company_name": "Cohere",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "ML Engineer",
    "required_skills": ["Python", "NLP", "Transformers", "LLMs"],
    "experience_required": "0-2 years",
    "package_lpa": 24.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/AI",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 30,
    "company_name": "Databricks",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer - ML",
    "required_skills": ["Scala", "Spark", "Machine Learning", "Big Data"],
    "experience_required": "0-2 years",
    "package_lpa": 20.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  }
]
